import json, urllib.request
m = json.load(urllib.request.urlopen("http://127.0.0.1:8765/memory.json", timeout=5))
st = json.load(urllib.request.urlopen("http://127.0.0.1:8765/bridge-status.json", timeout=5))
f = json.load(urllib.request.urlopen("http://127.0.0.1:8765/flow.json", timeout=5))
active = json.load(urllib.request.urlopen("http://127.0.0.1:8765/active_strategy.json", timeout=5))
print("=== 实际状态 ===")
print("anomaly:", m.get("anomaly_state"), "stuck:", m.get("stuck_duration"))
print("pos_y:", (st.get("pose") or [0,0,0,0])[1])
print("disp:", m.get("disp_60s"), "health:", m.get("health_score"))
print("decision:", f.get("decision_source"), "cpg_active:", (f.get("cpg_status") or {}).get("active"))
print("applied:", (st.get("x"), st.get("y")), "jump:", st.get("jump"))
print("\n=== 教练策略（已被 active_strategy.json 接受）===")
print("mode:", active.get("fallen_recovery", {}).get("mode"))
print("command:", active.get("command"))
print("escape.stuck_threshold:", active.get("escape", {}).get("stuck_threshold_s"))
print("\n=== 为什么没生效 ===")
print("1. 教练看到截图显示'墙体·通道'——正常室内场景")
print("2. 教练不知道 y=-954（虚空）—— 无 pos_y 传参")
print("3. heading=220° 的地面转向指令在虚空无效")
print("4. directional_climb 需要斜坡碰撞——虚空无碰撞")